name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Koodi allalaadimine
        uses: actions/checkout@v3

      - name: Node.js seadistamine
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Sõltuvuste paigaldamine
        run: npm install

      - name: Rakenduse ehitamine
        run: npm run build

      - name: Deploy GitHub Pages'ile
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: frontend/dist
